apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-redis-pvc
  namespace: production
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
