kind: Service
apiVersion: v1
metadata:
    name: my-backend-service
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 5000
          targetPort: 5000
          protocol: TCP
    selector:
        app: myapp
        type: backend
