apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-redis-dev
    namespace: development
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 50Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        #    Path dla Linux - nie działa
        path:
            "/mnt/data/development/redis"
            #    Path dla Windows - działa
            # path: "/run/desktop/mnt/host/d/Szkoła/Rok 2 semestr 2/Technologie chmurowe/Technologie_chmurowe/Projekt/development/data/redis"
    claimRef:
        name: my-redis-pvc
        namespace: development
