apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-mongodb-pvc
  namespace: development
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
