kind: Service
apiVersion: v1
metadata:
    name: my-frontend-service
    namespace: development
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
    selector:
        app: myapp
        type: frontend
