kind: Service
apiVersion: v1
metadata:
  name: my-mongodb-service
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    run: my-mongodb-deployment
