kind: Service
apiVersion: v1
metadata:
  name: my-redis-service
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    run: my-redis-deployment
